config/routes.rb
Rails.application.routes.draw do
  devise_for :teachers

  namespace :teachers do
    resources :classrooms
    resources :google_sessions
  end

  root to: "dashboards#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/classroom.rb
class Classroom < ApplicationRecord
  validates :name, presence: true
end

app/models/google_auth_credentials.rb
require 'singleton'

class GoogleAuthCredentials
  include Singleton

  def initialize
    @auth_instance = Google::Auth::UserRefreshCredentials.new(additional_parameters: {
        "include_granted_scopes" => "true",
        "prompt" => "consent"
      },
      client_id: "571945631403-ddvmgutmjcshtcrj8i1e58vmi9oobarn.apps.googleusercontent.com",
      client_secret: "YDUtQi_YY5E9wJO1BeWWxKdm",
      scope: [
        "https://www.googleapis.com/auth/drive",
        "https://spreadsheets.google.com/feeds/",
      ],
      redirect_uri: "http://localhost:3000/teachers/google_sessions/new"
    )
  end

  def auth_credentials
    @auth_instance
  end

  def refresh_token
    @auth_instance.refresh_token
  end
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index

  end
end

app/controllers/teachers/base_controller.rb
module Teachers
  class BaseController < ApplicationController
    before_action :check_google_client, :google_session

    private

    def check_google_client
      Rails.logger.info(session[:refresh_token])
      if !session[:refresh_token]
        redirect_to google_auth_authorization_uri
      else
        google_auth_credentials.refresh_token = session[:refresh_token]
        #google_auth_credentials.fetch_access_token!
      end
    end


    def google_session
      @google_session ||=
        GoogleDrive::Session.from_credentials(google_auth_credentials)
    end

    def google_auth_credentials
      GoogleAuthCredentials.instance.auth_credentials
    end

    def google_auth_authorization_uri
      GoogleAuthCredentials.instance.auth_credentials.authorization_uri.to_s
    end
  end
end

app/controllers/teachers/classrooms_controller.rb
module Teachers
  class ClassroomsController < BaseController
    before_action :set_classroom, only: [:edit, :create, :destroy]

    def index
      @classrooms = Classroom.all
    end

    def new
      @classroom = Classroom.new
    end

    def edit
    end

    def update

    end

    def create
      @classroom = ClassroomDecorator.new(@classroom).create(permitted_attributes(Classroom))

      if @classroom.save
        redirect_to teacher_classrooms_path
      else
        render :new
      end
    end

    def destroy

    end

    private

    def set_classroom
      @classroom = Classroom.find(params[:id])
    end
  end
end

app/controllers/teachers/google_sessions_controller.rb
module Teachers
  class GoogleSessionsController < BaseController
    skip_before_action :check_google_client

    def new
      google_auth_credentials.code = params[:code]
      google_auth_credentials.fetch_access_token!
      session[:refresh_token] = GoogleAuthCredentials.instance.refresh_token
      redirect_to teachers_classrooms_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title MyClassManager
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/teachers/classrooms/_form.html.erb
<%= simple_form_for @classroom do |f| %>
  <%= f.input :name %>
  <%= f.button :submit%>
<% end %>

app/views/teachers/classrooms/_form.html.haml
= simple_form_for @classroom do |f|
  = f.input :name
  = f.button :submit

app/views/teachers/classrooms/index.html.erb
<%= link_to "new classroom", new_teachers_classroom_path(code: params[:code]) %>

app/views/teachers/classrooms/index.html.haml
= link_to "new classroom", new_teachers_classroom_path(code: params[:code])

app/views/teachers/classrooms/new.html.erb
<%= render 'form' %>

app/views/teachers/classrooms/new.html.haml
= render 'form'